name: Build and format

on:
  push:
    branches: [ dev, ptb, stable ]
  pull_request:
    branches: [ dev, ptb, stable ]

jobs:
  formatandbuild:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Format
      run: dotnet format .\src\SharpPackageManager\SharpPackageManager.csproj
    - name: Build
      run: dotnet build .\src\SharpPackageManager\SharpPackageManager.csproj
    - name: Add
      run: git add . && git config user.name "Bultek Formatter" && git config user.email "help@bultek.com.ua"
    - name: Commit
      run: git commit -m --dry-run "format"
    - name: Push
      run: git push
